/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Files.Escritor;
import javax.swing.JSpinner; 
import javax.swing.SpinnerNumberModel;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;

/**
 *
 * @author l_a_b
 */
public class Parametros extends javax.swing.JFrame {
    private Menu menu;

    /**
     * Creates new form Parametros
     */
    public Parametros(Menu menu) {
        this.menu = menu;
        initComponents();
    }
    
    public boolean verifyMax(int[] parameters){
        int count = 0;
        for(int i = 0; i<parameters.length;i++){
            count += parameters[i];
        }
        if(count>11){
            JOptionPane.showMessageDialog(null, "¡Debe haber máximo 11 productores!");
            return false;
        }else return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jSpinner4 = new javax.swing.JSpinner();
        jSpinner5 = new javax.swing.JSpinner();
        jSpinner6 = new javax.swing.JSpinner();
        jSpinner7 = new javax.swing.JSpinner();
        jSpinner8 = new javax.swing.JSpinner();
        jSpinner9 = new javax.swing.JSpinner();
        jSpinner10 = new javax.swing.JSpinner();
        jSpinner11 = new javax.swing.JSpinner();
        jSpinner12 = new javax.swing.JSpinner();
        jSpinner13 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Tiempo (en seg) que dura un día:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 260, -1));

        jLabel3.setText("Cantidad de Días entre Entregas:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 250, -1));

        jLabel4.setText("Capacidad Máxima de Chasis:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 190, -1));

        jLabel5.setText("Capacidad Máxima de Carrocerías:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 190, -1));

        jLabel6.setText("Capacidad Máxima de Motores:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 190, -1));

        jLabel7.setText("Capacidad Máxima de Ruedas:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 190, -1));

        jLabel8.setText("Capacidad Máxima de Accesorios:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 190, -1));

        jLabel9.setText("Cantidad Inicial de Cread de Chasis:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 230, -1));

        jLabel10.setText("Cantidad Inicial de Cread de Carrocerías:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 230, -1));

        jLabel11.setText("Cantidad Inicial de Cread de Motores:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 230, -1));

        jLabel12.setText("Cantidad Inicial de Cread de Ruedas:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 230, -1));

        jLabel13.setText("Cantidad Inicial de Cread de Accesorios:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 230, -1));

        jLabel14.setText("Cantidad Inicial de Ensambladores:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 240, -1));

        jSpinner1.setModel(new SpinnerNumberModel(1, 1, 1000, 1));
        JFormattedTextField tf = ((JSpinner.DefaultEditor)jSpinner1.getEditor())
        .getTextField();
        tf.setEditable(false);
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, -1));

        jSpinner2.setModel(new SpinnerNumberModel(1, 1, 1000, 1));
        JFormattedTextField tf1 = ((JSpinner.DefaultEditor)jSpinner2.getEditor())
        .getTextField();
        tf1.setEditable(false);
        jPanel1.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        jSpinner3.setModel(new SpinnerNumberModel(1, 1, 1000, 1));
        JFormattedTextField tf2 = ((JSpinner.DefaultEditor)jSpinner3.getEditor())
        .getTextField();
        tf2.setEditable(false);
        jPanel1.add(jSpinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        jSpinner4.setModel(new SpinnerNumberModel(1, 1, 1000, 1));
        JFormattedTextField tf3 = ((JSpinner.DefaultEditor)jSpinner4.getEditor())
        .getTextField();
        tf3.setEditable(false);
        jPanel1.add(jSpinner4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));

        jSpinner5.setModel(new SpinnerNumberModel(1, 1, 1000, 1));
        JFormattedTextField tf4 = ((JSpinner.DefaultEditor)jSpinner5.getEditor())
        .getTextField();
        tf4.setEditable(false);
        jPanel1.add(jSpinner5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        jSpinner6.setModel(new SpinnerNumberModel(1, 1, 1000, 1));
        JFormattedTextField tf5 = ((JSpinner.DefaultEditor)jSpinner6.getEditor())
        .getTextField();
        tf5.setEditable(false);
        jPanel1.add(jSpinner6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));

        jSpinner7.setModel(new SpinnerNumberModel(1, 1, 1000, 1));
        JFormattedTextField tf6 = ((JSpinner.DefaultEditor)jSpinner7.getEditor())
        .getTextField();
        tf6.setEditable(false);
        jPanel1.add(jSpinner7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        jSpinner8.setModel(new SpinnerNumberModel(1, 1, 1000, 1));
        JFormattedTextField tf7 = ((JSpinner.DefaultEditor)jSpinner8.getEditor())
        .getTextField();
        tf7.setEditable(false);
        jPanel1.add(jSpinner8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        jSpinner9.setModel(new SpinnerNumberModel(1, 1, 1000, 1));
        JFormattedTextField tf8 = ((JSpinner.DefaultEditor)jSpinner9.getEditor())
        .getTextField();
        tf8.setEditable(false);
        jPanel1.add(jSpinner9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));

        jSpinner10.setModel(new SpinnerNumberModel(1, 1, 1000, 1));
        JFormattedTextField tf9 = ((JSpinner.DefaultEditor)jSpinner10.getEditor())
        .getTextField();
        tf9.setEditable(false);
        jPanel1.add(jSpinner10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, -1));

        jSpinner11.setModel(new SpinnerNumberModel(1, 1, 1000, 1));
        JFormattedTextField tf10 = ((JSpinner.DefaultEditor)jSpinner11.getEditor())
        .getTextField();
        tf10.setEditable(false);
        jPanel1.add(jSpinner11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, -1));

        jSpinner12.setModel(new SpinnerNumberModel(1, 1, 1000, 1));
        JFormattedTextField tf11 = ((JSpinner.DefaultEditor)jSpinner12.getEditor())
        .getTextField();
        tf11.setEditable(false);
        jPanel1.add(jSpinner12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, -1, -1));

        jSpinner13.setModel(new SpinnerNumberModel(1, 1, 1000, 1));
        JFormattedTextField tf12 = ((JSpinner.DefaultEditor)jSpinner13.getEditor())
        .getTextField();
        tf12.setEditable(false);
        jPanel1.add(jSpinner13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Escritor e1 = new Escritor();
        int[] parameters = new int[13];
        int[] producers = new int[5];
        parameters[0] = Integer.parseInt(jSpinner1.getValue().toString());
        parameters[1] = Integer.parseInt(jSpinner2.getValue().toString());
        parameters[2] = Integer.parseInt(jSpinner3.getValue().toString());
        parameters[3] = Integer.parseInt(jSpinner4.getValue().toString());
        parameters[4] = Integer.parseInt(jSpinner5.getValue().toString());
        parameters[5] = Integer.parseInt(jSpinner6.getValue().toString());
        parameters[6] = Integer.parseInt(jSpinner7.getValue().toString());
        parameters[7] = Integer.parseInt(jSpinner8.getValue().toString());
        parameters[8] = Integer.parseInt(jSpinner9.getValue().toString());
        parameters[9] = Integer.parseInt(jSpinner10.getValue().toString());
        parameters[10] = Integer.parseInt(jSpinner11.getValue().toString());
        parameters[11] = Integer.parseInt(jSpinner12.getValue().toString());
        parameters[12] = Integer.parseInt(jSpinner13.getValue().toString());

        for(int i = 0; i<producers.length; i++){
            producers[i]=parameters[7+i];
        }

        if(verifyMax(producers)){
            e1.CreateFile();
            e1.WriteToFile(parameters);
            this.dispose();
            this.menu.getLector().readFile(e1.getFile());
        };

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Parametros().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner10;
    private javax.swing.JSpinner jSpinner11;
    private javax.swing.JSpinner jSpinner12;
    private javax.swing.JSpinner jSpinner13;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JSpinner jSpinner7;
    private javax.swing.JSpinner jSpinner8;
    private javax.swing.JSpinner jSpinner9;
    // End of variables declaration//GEN-END:variables
}
